#%RAML 1.0 NamedExample
[
 {
 "companyCode":"TransNational",
 "originLocation": {
 "locationCode": "BEN-SG",
 "locationDesc": "Beauna Vista Singapore"
 },
 "destinationLocation": {
 "locationCode": "KLG-MY",
 "locationDesc": "Klang Malaysia"
 }
 }
]